// mockData.js (plain JS)

export const mockUsers = [
  { id: '1', email: 'john@example.com', name: 'John Doe' },
  { id: '2', email: 'jane@example.com', name: 'Jane Smith' },
  { id: '3', email: 'bob@example.com', name: 'Bob Johnson' },
  { id: '4', email: 'alice@example.com', name: 'Alice Brown' },
];

export const mockTasks = [
  {
    id: '1',
    title: 'Design homepage mockups',
    description: 'Create wireframes and high-fidelity mockups for the new homepage design',
    priority: 'High',
    assigneeId: '1',
    assigneeName: 'John Doe',
    status: 'In Progress',
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    created: new Date().toISOString(),
    updated: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Set up CI/CD pipeline',
    description: 'Configure automated testing and deployment pipeline',
    priority: 'Medium',
    assigneeId: '2',
    assigneeName: 'Jane Smith',
    status: 'Backlog',
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    created: new Date().toISOString(),
    updated: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'User authentication system',
    description: 'Implement JWT-based authentication with login and signup',
    priority: 'High',
    assigneeId: '3',
    assigneeName: 'Bob Johnson',
    status: 'Review',
    dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    created: new Date().toISOString(),
    updated: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'Write project documentation',
    description: 'Create comprehensive documentation for the project setup and API',
    priority: 'Low',
    assigneeId: '4',
    assigneeName: 'Alice Brown',
    status: 'Done',
    dueDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    created: new Date().toISOString(),
    updated: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'Database schema design',
    description: 'Design the database schema for users, tasks, and comments',
    priority: 'High',
    assigneeId: '1',
    assigneeName: 'John Doe',
    status: 'Backlog',
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    created: new Date().toISOString(),
    updated: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'Mobile responsive design',
    description: 'Ensure the application works perfectly on mobile devices',
    priority: 'Medium',
    assigneeId: '2',
    assigneeName: 'Jane Smith',
    status: 'In Progress',
    dueDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    created: new Date().toISOString(),
    updated: new Date().toISOString(),
  },
];
